#from ez_setup import use_setuptools
#use_setuptools()
from setuptools import setup, find_packages

# versiones use tags autogenerated with git hooks
VERSION = open('VERSION').read().lstrip('version: ').rstrip('\n')


setup(name="DjangoTemplatePreviewer",
      version=VERSION,
      description="Small django app to preview templates",
      long_description="""

""",
      author="Jeff Corcoran (forker)",
      author_email="jcorcoran+github@gmail.com",
      packages=find_packages(),
      install_requires=['pyyaml','setuptools_git >= 0.3',],
      )
